version: '3.9'
services:
  # db:
  #   image: mysql:5.7
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
  # wordpress:
  #   depends_on:
  #     - db
  #   image: wordpress:latest
  #   ports:
  #     - "8080:80"
  #   restart: always
  #   environment:
  #     WORDPRESS_DB_HOST: db:3306
  #     WORDPRESS_DB_USER: root
  #     WORDPRESS_DB_PASSWORD: example
  #     WORDPRESS_DB_NAME: wordpress
  #   volumes:
  #     - ./wordpress:/var/www/html
  #     - /var/www/html/wp-content/uploads:/var/www/html/wp-content/uploads
  #   container_name: wordpress
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    environment:
      DEFAULT_HOST: "flahoud.42.fr"
ENABLE_IPV6: "false"
        - "DEFAULT_EMAIL=your-email@example.com"
        - "DEFAULT_RESOLVER=1.1.1.1"
        - "DEFAULT_CERTIFICATE_RESOLVER=default_resolver"
    container_name: nginx

# volumes:
#   db_data: