version: '3'

services:
  db:
    container_name: db
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    networks:
      - wp_site
  wordpress:
    container_name: wordpress
    depends_on:
      - db
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    volumes:
      - /data/html:/var/www/html
    restart: always
    env_file:
      - .env
    links:
      - db
    ports:
      - "8000:80"
    networks:
      - wp_site
  nginx:
    image: nginx:alpine
    volumes:
      - nginx:/etc/nginx/conf.d
      - /data/html:/var/www/html
    ports:
      - 8080:80
    links:
      - wordpress

volumes:
  db_data:
  wordpress_data:

networks:
  wp_site:
    driver: bridge
