SET @db_user = '$MYSQL_USER';
SET @db_password = '$MYSQL_PASSWORD';
SET @db_name = '$MYSQL_DATABASE';

USE mysql;
CREATE DATABASE IF NOT EXISTS ${DB_NAME};
CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASSWORD}';
GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'%';
FLUSH PRIVILEGES;

